<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ProjectType>ProgramLibrary</ProjectType>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>net8</TargetFramework>
    <RootNamespace>PepperDash.Essentials.Plugins</RootNamespace>
    <Deterministic>false</Deterministic>
    <AssemblyTitle>PepperDash.Essentials.Plugins.Crestron.Io</AssemblyTitle>
    <Company>PepperDash Technologies</Company>
    <Description>This software is a plugin designed to work as a part of PepperDash Essentials for Crestron control processors. This plugin allows for control of Crestron IO devices.</Description>
    <Copyright>Copyright 2024</Copyright>
    <Version>1.0.0-local</Version>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <InformationalVersion>$(Version)</InformationalVersion>
    <OutputPath>4Series\bin\$(Configuration)\</OutputPath>
    <Authors>PepperDash Technologies</Authors>
    <AssemblyName>PepperDash.Essentials.Plugins.Crestron.Io</AssemblyName>
    <PackageId>PepperDash.Essentials.Plugins.Crestron.Io</PackageId>
    <PackageProjectUrl>https://github.com/PepperDash/epi-crestron-io</PackageProjectUrl>
    <PackageTags>crestron 4series io</PackageTags> 
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    </PropertyGroup>
  

  <ItemGroup>
    <Compile Remove="Properties\**" />
    <EmbeddedResource Remove="Properties\**" />
    <None Remove="Properties\**" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="PepperDashEssentials" Version="3.0.0-fix-surface-masked-device-instantiation-errors.1" >
		  <ExcludeAssets>runtime</ExcludeAssets>
	  </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Remove="../output\epi-crestron-io.4Series.1.0.0-local.cplz" />
  </ItemGroup>
</Project>
